package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Analisisvaloracion generated by hbm2java
 */
public class Analisisvaloracion  implements java.io.Serializable {


     private int idanalisisvaloracion;
     private Panorama panorama;
     private int origen;
     private int probabilidad;
     private int impacto;
     private int control;
     private String color;
     private Set trazavaloracions = new HashSet(0);

    public Analisisvaloracion() {
    }

	
    public Analisisvaloracion(int idanalisisvaloracion, Panorama panorama, int origen, int probabilidad, int impacto, int control, String color) {
        this.idanalisisvaloracion = idanalisisvaloracion;
        this.panorama = panorama;
        this.origen = origen;
        this.probabilidad = probabilidad;
        this.impacto = impacto;
        this.control = control;
        this.color = color;
    }
    public Analisisvaloracion(int idanalisisvaloracion, Panorama panorama, int origen, int probabilidad, int impacto, int control, String color, Set trazavaloracions) {
       this.idanalisisvaloracion = idanalisisvaloracion;
       this.panorama = panorama;
       this.origen = origen;
       this.probabilidad = probabilidad;
       this.impacto = impacto;
       this.control = control;
       this.color = color;
       this.trazavaloracions = trazavaloracions;
    }
   
    public int getIdanalisisvaloracion() {
        return this.idanalisisvaloracion;
    }
    
    public void setIdanalisisvaloracion(int idanalisisvaloracion) {
        this.idanalisisvaloracion = idanalisisvaloracion;
    }
    public Panorama getPanorama() {
        return this.panorama;
    }
    
    public void setPanorama(Panorama panorama) {
        this.panorama = panorama;
    }
    public int getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(int origen) {
        this.origen = origen;
    }
    public int getProbabilidad() {
        return this.probabilidad;
    }
    
    public void setProbabilidad(int probabilidad) {
        this.probabilidad = probabilidad;
    }
    public int getImpacto() {
        return this.impacto;
    }
    
    public void setImpacto(int impacto) {
        this.impacto = impacto;
    }
    public int getControl() {
        return this.control;
    }
    
    public void setControl(int control) {
        this.control = control;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getTrazavaloracions() {
        return this.trazavaloracions;
    }
    
    public void setTrazavaloracions(Set trazavaloracions) {
        this.trazavaloracions = trazavaloracions;
    }




}


