package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private int idciudad;
     private Departamento departamento;
     private String codigociudad;
     private String descciudad;
     private Set funcionariosForIdciudad = new HashSet(0);
     private Set subareas = new HashSet(0);
     private Set funcionariosForCiuIdciudad = new HashSet(0);
     private Set funcionariosForCiuIdciudad2 = new HashSet(0);

    public Ciudad() {
    }

	
    public Ciudad(int idciudad, Departamento departamento, String codigociudad, String descciudad) {
        this.idciudad = idciudad;
        this.departamento = departamento;
        this.codigociudad = codigociudad;
        this.descciudad = descciudad;
    }
    public Ciudad(int idciudad, Departamento departamento, String codigociudad, String descciudad, Set funcionariosForIdciudad, Set subareas, Set funcionariosForCiuIdciudad, Set funcionariosForCiuIdciudad2) {
       this.idciudad = idciudad;
       this.departamento = departamento;
       this.codigociudad = codigociudad;
       this.descciudad = descciudad;
       this.funcionariosForIdciudad = funcionariosForIdciudad;
       this.subareas = subareas;
       this.funcionariosForCiuIdciudad = funcionariosForCiuIdciudad;
       this.funcionariosForCiuIdciudad2 = funcionariosForCiuIdciudad2;
    }
   
    public int getIdciudad() {
        return this.idciudad;
    }
    
    public void setIdciudad(int idciudad) {
        this.idciudad = idciudad;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getCodigociudad() {
        return this.codigociudad;
    }
    
    public void setCodigociudad(String codigociudad) {
        this.codigociudad = codigociudad;
    }
    public String getDescciudad() {
        return this.descciudad;
    }
    
    public void setDescciudad(String descciudad) {
        this.descciudad = descciudad;
    }
    public Set getFuncionariosForIdciudad() {
        return this.funcionariosForIdciudad;
    }
    
    public void setFuncionariosForIdciudad(Set funcionariosForIdciudad) {
        this.funcionariosForIdciudad = funcionariosForIdciudad;
    }
    public Set getSubareas() {
        return this.subareas;
    }
    
    public void setSubareas(Set subareas) {
        this.subareas = subareas;
    }
    public Set getFuncionariosForCiuIdciudad() {
        return this.funcionariosForCiuIdciudad;
    }
    
    public void setFuncionariosForCiuIdciudad(Set funcionariosForCiuIdciudad) {
        this.funcionariosForCiuIdciudad = funcionariosForCiuIdciudad;
    }
    public Set getFuncionariosForCiuIdciudad2() {
        return this.funcionariosForCiuIdciudad2;
    }
    
    public void setFuncionariosForCiuIdciudad2(Set funcionariosForCiuIdciudad2) {
        this.funcionariosForCiuIdciudad2 = funcionariosForCiuIdciudad2;
    }




}


