package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int iddepartamento;
     private String codigodepartamento;
     private String descdepartamento;
     private Set ciudads = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int iddepartamento, String codigodepartamento, String descdepartamento) {
        this.iddepartamento = iddepartamento;
        this.codigodepartamento = codigodepartamento;
        this.descdepartamento = descdepartamento;
    }
    public Departamento(int iddepartamento, String codigodepartamento, String descdepartamento, Set ciudads) {
       this.iddepartamento = iddepartamento;
       this.codigodepartamento = codigodepartamento;
       this.descdepartamento = descdepartamento;
       this.ciudads = ciudads;
    }
   
    public int getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public String getCodigodepartamento() {
        return this.codigodepartamento;
    }
    
    public void setCodigodepartamento(String codigodepartamento) {
        this.codigodepartamento = codigodepartamento;
    }
    public String getDescdepartamento() {
        return this.descdepartamento;
    }
    
    public void setDescdepartamento(String descdepartamento) {
        this.descdepartamento = descdepartamento;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }




}


