package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Nombreproceso generated by hbm2java
 */
public class Nombreproceso  implements java.io.Serializable {


     private int idnombreproceso;
     private Tipoproceso tipoproceso;
     private String descnombre;
     private Set procesoasociados = new HashSet(0);

    public Nombreproceso() {
    }

	
    public Nombreproceso(int idnombreproceso, Tipoproceso tipoproceso, String descnombre) {
        this.idnombreproceso = idnombreproceso;
        this.tipoproceso = tipoproceso;
        this.descnombre = descnombre;
    }
    public Nombreproceso(int idnombreproceso, Tipoproceso tipoproceso, String descnombre, Set procesoasociados) {
       this.idnombreproceso = idnombreproceso;
       this.tipoproceso = tipoproceso;
       this.descnombre = descnombre;
       this.procesoasociados = procesoasociados;
    }
   
    public int getIdnombreproceso() {
        return this.idnombreproceso;
    }
    
    public void setIdnombreproceso(int idnombreproceso) {
        this.idnombreproceso = idnombreproceso;
    }
    public Tipoproceso getTipoproceso() {
        return this.tipoproceso;
    }
    
    public void setTipoproceso(Tipoproceso tipoproceso) {
        this.tipoproceso = tipoproceso;
    }
    public String getDescnombre() {
        return this.descnombre;
    }
    
    public void setDescnombre(String descnombre) {
        this.descnombre = descnombre;
    }
    public Set getProcesoasociados() {
        return this.procesoasociados;
    }
    
    public void setProcesoasociados(Set procesoasociados) {
        this.procesoasociados = procesoasociados;
    }




}


