package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private int idperfil;
     private Estado estado;
     private String descperfil;
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(int idperfil, Estado estado, String descperfil) {
        this.idperfil = idperfil;
        this.estado = estado;
        this.descperfil = descperfil;
    }
    public Perfil(int idperfil, Estado estado, String descperfil, Set usuarios) {
       this.idperfil = idperfil;
       this.estado = estado;
       this.descperfil = descperfil;
       this.usuarios = usuarios;
    }
   
    public int getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(int idperfil) {
        this.idperfil = idperfil;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getDescperfil() {
        return this.descperfil;
    }
    
    public void setDescperfil(String descperfil) {
        this.descperfil = descperfil;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


