package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proceso generated by hbm2java
 */
public class Proceso  implements java.io.Serializable {


     private int idproceso;
     private Estado estado;
     private Subarea subarea;
     private Procesoasociado procesoasociado;
     private Funcionario funcionario;
     private String codigoproceso;
     private Date creado;
     private Date modificado;
     private Set panoramas = new HashSet(0);
     private Set trazaprocesos = new HashSet(0);

    public Proceso() {
    }

	
    public Proceso(int idproceso, Estado estado, Subarea subarea, Procesoasociado procesoasociado, Funcionario funcionario, String codigoproceso, Date creado) {
        this.idproceso = idproceso;
        this.estado = estado;
        this.subarea = subarea;
        this.procesoasociado = procesoasociado;
        this.funcionario = funcionario;
        this.codigoproceso = codigoproceso;
        this.creado = creado;
    }
    public Proceso(int idproceso, Estado estado, Subarea subarea, Procesoasociado procesoasociado, Funcionario funcionario, String codigoproceso, Date creado, Date modificado, Set panoramas, Set trazaprocesos) {
       this.idproceso = idproceso;
       this.estado = estado;
       this.subarea = subarea;
       this.procesoasociado = procesoasociado;
       this.funcionario = funcionario;
       this.codigoproceso = codigoproceso;
       this.creado = creado;
       this.modificado = modificado;
       this.panoramas = panoramas;
       this.trazaprocesos = trazaprocesos;
    }
   
    public int getIdproceso() {
        return this.idproceso;
    }
    
    public void setIdproceso(int idproceso) {
        this.idproceso = idproceso;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Subarea getSubarea() {
        return this.subarea;
    }
    
    public void setSubarea(Subarea subarea) {
        this.subarea = subarea;
    }
    public Procesoasociado getProcesoasociado() {
        return this.procesoasociado;
    }
    
    public void setProcesoasociado(Procesoasociado procesoasociado) {
        this.procesoasociado = procesoasociado;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getCodigoproceso() {
        return this.codigoproceso;
    }
    
    public void setCodigoproceso(String codigoproceso) {
        this.codigoproceso = codigoproceso;
    }
    public Date getCreado() {
        return this.creado;
    }
    
    public void setCreado(Date creado) {
        this.creado = creado;
    }
    public Date getModificado() {
        return this.modificado;
    }
    
    public void setModificado(Date modificado) {
        this.modificado = modificado;
    }
    public Set getPanoramas() {
        return this.panoramas;
    }
    
    public void setPanoramas(Set panoramas) {
        this.panoramas = panoramas;
    }
    public Set getTrazaprocesos() {
        return this.trazaprocesos;
    }
    
    public void setTrazaprocesos(Set trazaprocesos) {
        this.trazaprocesos = trazaprocesos;
    }




}


