package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Regional generated by hbm2java
 */
public class Regional  implements java.io.Serializable {


     private int idregional;
     private String codigoregional;
     private String descregional;
     private Set seccionals = new HashSet(0);

    public Regional() {
    }

	
    public Regional(int idregional, String codigoregional, String descregional) {
        this.idregional = idregional;
        this.codigoregional = codigoregional;
        this.descregional = descregional;
    }
    public Regional(int idregional, String codigoregional, String descregional, Set seccionals) {
       this.idregional = idregional;
       this.codigoregional = codigoregional;
       this.descregional = descregional;
       this.seccionals = seccionals;
    }
   
    public int getIdregional() {
        return this.idregional;
    }
    
    public void setIdregional(int idregional) {
        this.idregional = idregional;
    }
    public String getCodigoregional() {
        return this.codigoregional;
    }
    
    public void setCodigoregional(String codigoregional) {
        this.codigoregional = codigoregional;
    }
    public String getDescregional() {
        return this.descregional;
    }
    
    public void setDescregional(String descregional) {
        this.descregional = descregional;
    }
    public Set getSeccionals() {
        return this.seccionals;
    }
    
    public void setSeccionals(Set seccionals) {
        this.seccionals = seccionals;
    }




}


