package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Seccional generated by hbm2java
 */
public class Seccional  implements java.io.Serializable {


     private int idseccional;
     private Regional regional;
     private String codigoseccional;
     private String descseccional;
     private Set areas = new HashSet(0);

    public Seccional() {
    }

	
    public Seccional(int idseccional, Regional regional, String codigoseccional, String descseccional) {
        this.idseccional = idseccional;
        this.regional = regional;
        this.codigoseccional = codigoseccional;
        this.descseccional = descseccional;
    }
    public Seccional(int idseccional, Regional regional, String codigoseccional, String descseccional, Set areas) {
       this.idseccional = idseccional;
       this.regional = regional;
       this.codigoseccional = codigoseccional;
       this.descseccional = descseccional;
       this.areas = areas;
    }
   
    public int getIdseccional() {
        return this.idseccional;
    }
    
    public void setIdseccional(int idseccional) {
        this.idseccional = idseccional;
    }
    public Regional getRegional() {
        return this.regional;
    }
    
    public void setRegional(Regional regional) {
        this.regional = regional;
    }
    public String getCodigoseccional() {
        return this.codigoseccional;
    }
    
    public void setCodigoseccional(String codigoseccional) {
        this.codigoseccional = codigoseccional;
    }
    public String getDescseccional() {
        return this.descseccional;
    }
    
    public void setDescseccional(String descseccional) {
        this.descseccional = descseccional;
    }
    public Set getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set areas) {
        this.areas = areas;
    }




}


