package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Trazariesgo generated by hbm2java
 */
public class Trazariesgo  implements java.io.Serializable {


     private int idtrazariesgo;
     private Riesgo riesgo;
     private String trazanombre;
     private String trazadescripcion;
     private String trazaclasificacion;
     private String trazaenfoque;
     private String trazatipo;
     private String usuariooperacion;
     private Date fechaoperacion;
     private String tipooperacion;

    public Trazariesgo() {
    }

    public Trazariesgo(int idtrazariesgo, Riesgo riesgo, String trazanombre, String trazadescripcion, String trazaclasificacion, String trazaenfoque, String trazatipo, String usuariooperacion, Date fechaoperacion, String tipooperacion) {
       this.idtrazariesgo = idtrazariesgo;
       this.riesgo = riesgo;
       this.trazanombre = trazanombre;
       this.trazadescripcion = trazadescripcion;
       this.trazaclasificacion = trazaclasificacion;
       this.trazaenfoque = trazaenfoque;
       this.trazatipo = trazatipo;
       this.usuariooperacion = usuariooperacion;
       this.fechaoperacion = fechaoperacion;
       this.tipooperacion = tipooperacion;
    }
   
    public int getIdtrazariesgo() {
        return this.idtrazariesgo;
    }
    
    public void setIdtrazariesgo(int idtrazariesgo) {
        this.idtrazariesgo = idtrazariesgo;
    }
    public Riesgo getRiesgo() {
        return this.riesgo;
    }
    
    public void setRiesgo(Riesgo riesgo) {
        this.riesgo = riesgo;
    }
    public String getTrazanombre() {
        return this.trazanombre;
    }
    
    public void setTrazanombre(String trazanombre) {
        this.trazanombre = trazanombre;
    }
    public String getTrazadescripcion() {
        return this.trazadescripcion;
    }
    
    public void setTrazadescripcion(String trazadescripcion) {
        this.trazadescripcion = trazadescripcion;
    }
    public String getTrazaclasificacion() {
        return this.trazaclasificacion;
    }
    
    public void setTrazaclasificacion(String trazaclasificacion) {
        this.trazaclasificacion = trazaclasificacion;
    }
    public String getTrazaenfoque() {
        return this.trazaenfoque;
    }
    
    public void setTrazaenfoque(String trazaenfoque) {
        this.trazaenfoque = trazaenfoque;
    }
    public String getTrazatipo() {
        return this.trazatipo;
    }
    
    public void setTrazatipo(String trazatipo) {
        this.trazatipo = trazatipo;
    }
    public String getUsuariooperacion() {
        return this.usuariooperacion;
    }
    
    public void setUsuariooperacion(String usuariooperacion) {
        this.usuariooperacion = usuariooperacion;
    }
    public Date getFechaoperacion() {
        return this.fechaoperacion;
    }
    
    public void setFechaoperacion(Date fechaoperacion) {
        this.fechaoperacion = fechaoperacion;
    }
    public String getTipooperacion() {
        return this.tipooperacion;
    }
    
    public void setTipooperacion(String tipooperacion) {
        this.tipooperacion = tipooperacion;
    }




}


