package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Trazapanorama generated by hbm2java
 */
public class Trazapanorama  implements java.io.Serializable {


     private int idtrazapanorama;
     private Panorama panorama;
     private String trazacausa;
     private String trazaefecto;
     private String usuariooperacion;
     private Date fechaoperacion;
     private String tipooperacion;

    public Trazapanorama() {
    }

	
    public Trazapanorama(int idtrazapanorama, String trazacausa, String trazaefecto, String usuariooperacion, Date fechaoperacion, String tipooperacion) {
        this.idtrazapanorama = idtrazapanorama;
        this.trazacausa = trazacausa;
        this.trazaefecto = trazaefecto;
        this.usuariooperacion = usuariooperacion;
        this.fechaoperacion = fechaoperacion;
        this.tipooperacion = tipooperacion;
    }
    public Trazapanorama(int idtrazapanorama, Panorama panorama, String trazacausa, String trazaefecto, String usuariooperacion, Date fechaoperacion, String tipooperacion) {
       this.idtrazapanorama = idtrazapanorama;
       this.panorama = panorama;
       this.trazacausa = trazacausa;
       this.trazaefecto = trazaefecto;
       this.usuariooperacion = usuariooperacion;
       this.fechaoperacion = fechaoperacion;
       this.tipooperacion = tipooperacion;
    }
   
    public int getIdtrazapanorama() {
        return this.idtrazapanorama;
    }
    
    public void setIdtrazapanorama(int idtrazapanorama) {
        this.idtrazapanorama = idtrazapanorama;
    }
    public Panorama getPanorama() {
        return this.panorama;
    }
    
    public void setPanorama(Panorama panorama) {
        this.panorama = panorama;
    }
    public String getTrazacausa() {
        return this.trazacausa;
    }
    
    public void setTrazacausa(String trazacausa) {
        this.trazacausa = trazacausa;
    }
    public String getTrazaefecto() {
        return this.trazaefecto;
    }
    
    public void setTrazaefecto(String trazaefecto) {
        this.trazaefecto = trazaefecto;
    }
    public String getUsuariooperacion() {
        return this.usuariooperacion;
    }
    
    public void setUsuariooperacion(String usuariooperacion) {
        this.usuariooperacion = usuariooperacion;
    }
    public Date getFechaoperacion() {
        return this.fechaoperacion;
    }
    
    public void setFechaoperacion(Date fechaoperacion) {
        this.fechaoperacion = fechaoperacion;
    }
    public String getTipooperacion() {
        return this.tipooperacion;
    }
    
    public void setTipooperacion(String tipooperacion) {
        this.tipooperacion = tipooperacion;
    }




}


