package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Trazamejora generated by hbm2java
 */
public class Trazamejora  implements java.io.Serializable {


     private int idtrazamejora;
     private Planmejoramiento planmejoramiento;
     private String proceso;
     private String riesgo;
     private String responsable;
     private Date fechainicio;
     private Date fecharevision;
     private int calificacion;
     private String estadomejoramiento;
     private String usuariooperacion;
     private Date fechaoperacion;
     private String tipooperacion;

    public Trazamejora() {
    }

	
    public Trazamejora(int idtrazamejora, Planmejoramiento planmejoramiento, String proceso, String riesgo, String responsable, Date fechainicio, Date fecharevision, int calificacion, String estadomejoramiento, String usuariooperacion, Date fechaoperacion) {
        this.idtrazamejora = idtrazamejora;
        this.planmejoramiento = planmejoramiento;
        this.proceso = proceso;
        this.riesgo = riesgo;
        this.responsable = responsable;
        this.fechainicio = fechainicio;
        this.fecharevision = fecharevision;
        this.calificacion = calificacion;
        this.estadomejoramiento = estadomejoramiento;
        this.usuariooperacion = usuariooperacion;
        this.fechaoperacion = fechaoperacion;
    }
    public Trazamejora(int idtrazamejora, Planmejoramiento planmejoramiento, String proceso, String riesgo, String responsable, Date fechainicio, Date fecharevision, int calificacion, String estadomejoramiento, String usuariooperacion, Date fechaoperacion, String tipooperacion) {
       this.idtrazamejora = idtrazamejora;
       this.planmejoramiento = planmejoramiento;
       this.proceso = proceso;
       this.riesgo = riesgo;
       this.responsable = responsable;
       this.fechainicio = fechainicio;
       this.fecharevision = fecharevision;
       this.calificacion = calificacion;
       this.estadomejoramiento = estadomejoramiento;
       this.usuariooperacion = usuariooperacion;
       this.fechaoperacion = fechaoperacion;
       this.tipooperacion = tipooperacion;
    }
   
    public int getIdtrazamejora() {
        return this.idtrazamejora;
    }
    
    public void setIdtrazamejora(int idtrazamejora) {
        this.idtrazamejora = idtrazamejora;
    }
    public Planmejoramiento getPlanmejoramiento() {
        return this.planmejoramiento;
    }
    
    public void setPlanmejoramiento(Planmejoramiento planmejoramiento) {
        this.planmejoramiento = planmejoramiento;
    }
    public String getProceso() {
        return this.proceso;
    }
    
    public void setProceso(String proceso) {
        this.proceso = proceso;
    }
    public String getRiesgo() {
        return this.riesgo;
    }
    
    public void setRiesgo(String riesgo) {
        this.riesgo = riesgo;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFecharevision() {
        return this.fecharevision;
    }
    
    public void setFecharevision(Date fecharevision) {
        this.fecharevision = fecharevision;
    }
    public int getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(int calificacion) {
        this.calificacion = calificacion;
    }
    public String getEstadomejoramiento() {
        return this.estadomejoramiento;
    }
    
    public void setEstadomejoramiento(String estadomejoramiento) {
        this.estadomejoramiento = estadomejoramiento;
    }
    public String getUsuariooperacion() {
        return this.usuariooperacion;
    }
    
    public void setUsuariooperacion(String usuariooperacion) {
        this.usuariooperacion = usuariooperacion;
    }
    public Date getFechaoperacion() {
        return this.fechaoperacion;
    }
    
    public void setFechaoperacion(Date fechaoperacion) {
        this.fechaoperacion = fechaoperacion;
    }
    public String getTipooperacion() {
        return this.tipooperacion;
    }
    
    public void setTipooperacion(String tipooperacion) {
        this.tipooperacion = tipooperacion;
    }




}


