package com.srp.persistencia;
// Generated 23/05/2015 08:59:36 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Trazaproceso generated by hbm2java
 */
public class Trazaproceso  implements java.io.Serializable {


     private int idtraza;
     private Proceso proceso;
     private String tipoproceso;
     private String nombreproceso;
     private String procesoasociado;
     private String subarea;
     private String funcionarioasociado;
     private String estado;
     private String usuariooperacion;
     private Date fechaoperacion;
     private String tipooperacion;

    public Trazaproceso() {
    }

    public Trazaproceso(int idtraza, Proceso proceso, String tipoproceso, String nombreproceso, String procesoasociado, String subarea, String funcionarioasociado, String estado, String usuariooperacion, Date fechaoperacion, String tipooperacion) {
       this.idtraza = idtraza;
       this.proceso = proceso;
       this.tipoproceso = tipoproceso;
       this.nombreproceso = nombreproceso;
       this.procesoasociado = procesoasociado;
       this.subarea = subarea;
       this.funcionarioasociado = funcionarioasociado;
       this.estado = estado;
       this.usuariooperacion = usuariooperacion;
       this.fechaoperacion = fechaoperacion;
       this.tipooperacion = tipooperacion;
    }
   
    public int getIdtraza() {
        return this.idtraza;
    }
    
    public void setIdtraza(int idtraza) {
        this.idtraza = idtraza;
    }
    public Proceso getProceso() {
        return this.proceso;
    }
    
    public void setProceso(Proceso proceso) {
        this.proceso = proceso;
    }
    public String getTipoproceso() {
        return this.tipoproceso;
    }
    
    public void setTipoproceso(String tipoproceso) {
        this.tipoproceso = tipoproceso;
    }
    public String getNombreproceso() {
        return this.nombreproceso;
    }
    
    public void setNombreproceso(String nombreproceso) {
        this.nombreproceso = nombreproceso;
    }
    public String getProcesoasociado() {
        return this.procesoasociado;
    }
    
    public void setProcesoasociado(String procesoasociado) {
        this.procesoasociado = procesoasociado;
    }
    public String getSubarea() {
        return this.subarea;
    }
    
    public void setSubarea(String subarea) {
        this.subarea = subarea;
    }
    public String getFuncionarioasociado() {
        return this.funcionarioasociado;
    }
    
    public void setFuncionarioasociado(String funcionarioasociado) {
        this.funcionarioasociado = funcionarioasociado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getUsuariooperacion() {
        return this.usuariooperacion;
    }
    
    public void setUsuariooperacion(String usuariooperacion) {
        this.usuariooperacion = usuariooperacion;
    }
    public Date getFechaoperacion() {
        return this.fechaoperacion;
    }
    
    public void setFechaoperacion(Date fechaoperacion) {
        this.fechaoperacion = fechaoperacion;
    }
    public String getTipooperacion() {
        return this.tipooperacion;
    }
    
    public void setTipooperacion(String tipooperacion) {
        this.tipooperacion = tipooperacion;
    }




}


